describe('App', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
    cy.get('button')
    cy.contains('Next')
    .click()
    cy.get('button')
    cy.contains('Next')
    .click()
    cy.get('button')
    cy.contains('Next')
    .click()
    cy.get('.jsx-1228826222')
    .click()
  })

  it("should display a title and a vav bar", () => {
    cy.contains('Crate')
    cy.contains('nav')
  })

  it("should be able to log in", () => {
    cy.get('[href="/user/login"]')
      .click()
    cy.get('input')
      .first()
      .type("user@crate.com")
    cy.get('input')
      .last()
      .type("123456")
    cy.get('button')
      .contains('Login')
      .click()
    cy.contains('Logging in, please wait...')
      .should('be.visible')
    cy.contains('Crates for everyone')
      .should('be.visible')
    cy.contains('Clothes for Men')
      .should('be.visible')
  })

  it("should be able to see user's info after login", () => {
    cy.get('[href="/user/login"]')
      .click()
    cy.get('input')
      .first()
      .type("user@crate.com")
    cy.get('input')
      .last()
      .type('123456')
    cy.get('button')
      .contains('Login')
      .click()
    cy.get('[href="/user/profile"]')
      .click()
    cy.contains('The User')
    .should('be.visible')
    cy.contains('user@crate.com')
    .should('be.visible')
    cy.contains('Shipping Address:')
    .should('be.visible')
    cy.contains('Description:')
      .should('be.visible')
    cy.get('img')
      .should('be.visible')
  })

  it("should be able to add a description", () => {
    cy.get('[href="/user/login"]')
      .click()
    cy.get('input')
      .first()
      .type("user@crate.com")
    cy.get('input')
      .last()
      .type('123456')
    cy.get('button')
      .contains('Login')
      .click()
    cy.get('[href="/user/profile"]')
      .click()
    cy.get('button')
      .contains('Edit Profile')
      .click()
    cy.get(':nth-child(3) > .jsx-3002558909')
      .type('{selectall}{backspace}')
      .type('This is a description').should('have.value', 'This is a description')
    cy.get('button')
      .contains('Save')
      .click()
    cy.contains('Profile saved successfully.')
    cy.get('[style="text-align: right;"] > div > [href="/user/profile"]')
    .click()
    cy.contains('This is a description')
      .should('be.visible')
  })

  it("should be able to add a shipping address", () => {
    cy.get('[href="/user/login"]')
      .click()
    cy.get('input')
      .first()
      .type("user@crate.com")
    cy.get('input')
      .last()
      .type('123456')
    cy.get('button')
      .contains('Login')
      .click()
    cy.get('[href="/user/profile"]')
      .click()
    cy.get('button')
      .contains('Edit Profile')
      .click()
    cy.get(':nth-child(2) > .jsx-3002558909')
      .type('{selectall}{backspace}')
      .type('123 Fakey Dr').should('have.value', '123 Fakey Dr')
    cy.get('button')
      .contains('Save')
      .click()
    cy.contains('Profile saved successfully.')
    cy.get('[style="text-align: right;"] > div > [href="/user/profile"]')
    .click()
    cy.contains('This is a description')
      .should('be.visible')
    cy.contains('123 Fakey Dr')
      .should('be.visible')
  })

  it("should show all current info as values in input fields for editing", () => {
    cy.get('[href="/user/login"]')
      .click()
    cy.get('input')
      .first()
      .type("user@crate.com")
    cy.get('input')
      .last()
      .type('123456')
    cy.get('button')
      .contains('Login')
      .click()
    cy.get('[href="/user/profile"]')
      .click()
    cy.get('button')
      .contains('Edit Profile')
      .click()
    cy.get('[style="width: 25em; margin: 0px auto;"] > :nth-child(1) > .jsx-3002558909')
      .should('have.value', 'user@crate.com')
    cy.get('[style="width: 25em; margin: 0px auto;"] > :nth-child(2) > .jsx-3002558909')
      .should('have.value', '123 Fakey Dr')
    cy.get('[style="width: 25em; margin: 0px auto;"] > :nth-child(3) > .jsx-3002558909')
      .should('have.value', 'This is a description')
  })
})